# https://github.com/github/super-linter
name: Program Code Linter

on:
  push:
    branches: [main]

jobs:
  ProgramCodeLinter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code in Repository
        uses: actions/checkout@v4

      - name: Lint JavaScript Program Code
        uses: github/super-linter@v5
        env:
          VALIDATE_JAVASCRIPT_ES: true
          FILTER_REGEX_INCLUDE: ./2.6-GitHubActions/ProgramCodeModified.js
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
